// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF4aWgkvUWQ9UOvl_S1Iwb1QBZeclUNYU',
    appId: '1:744697429882:web:ff14e2906e7badb0a2e0c3',
    messagingSenderId: '744697429882',
    projectId: 'signup-f10c8',
    authDomain: 'signup-f10c8.firebaseapp.com',
    databaseURL: 'https://signup-f10c8-default-rtdb.firebaseio.com',
    storageBucket: 'signup-f10c8.appspot.com',
    measurementId: 'G-ZYF47CGM48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNX5p1rEMOVOlebRSeYJB49zKfiGC_6jU',
    appId: '1:744697429882:android:76febbf5d802b6d7a2e0c3',
    messagingSenderId: '744697429882',
    projectId: 'signup-f10c8',
    databaseURL: 'https://signup-f10c8-default-rtdb.firebaseio.com',
    storageBucket: 'signup-f10c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOCedD8aRpfPPdfw-vhfDn-W8RALvJ79w',
    appId: '1:744697429882:ios:0c700cdf0b0e6c07a2e0c3',
    messagingSenderId: '744697429882',
    projectId: 'signup-f10c8',
    databaseURL: 'https://signup-f10c8-default-rtdb.firebaseio.com',
    storageBucket: 'signup-f10c8.appspot.com',
    androidClientId: '744697429882-0dv50u0vgcuql1400ki9brioje4un400.apps.googleusercontent.com',
    iosClientId: '744697429882-qgf4ub44afffv9jn1lhg9qds0uj8nmrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxAuthTest',
  );
}
